# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"

pytest:
  image: python:3.11.5-alpine
  stage: test
  script:
    - pip install -U pytest
    - pytest --version
    - pip install -r ./data_sources/us_bureau_of_labor_statistics/requirements.txt
    - cd ./data_sources/us_bureau_of_labor_statistics/test/
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: data_sources/us_bureau_of_labor_statistics/test/report.xml